parameters:
#    twig_twig.example.class: Twig\TwigBundle\Example

services:
#    twig_twig.example:
#        class: %twig_twig.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
